In [121]:
import psycopg2
import os
import pandas as pd
import ast
import re

from tqdm import tqdm
from dotenv import load_dotenv
load_dotenv()
pd.set_option('display.max_rows', 100000)
pd.set_option("max_colwidth", 500)
KEY_POSTGRES = os.getenv("KEY_POSTGRES")

In [64]:
DF_input = input().strip()

 C:\Users\svalb\OneDrive\Escritorio\Data_40_years_cancer_studies\preparedInstitutionsTestDatabaseAccess.csv

In [65]:
df = pd.read_csv(DF_input)

In [66]:
s = df.iloc[2]["NER_BERT"]

In [67]:
df.iloc[2]["Institutions_man"]

"['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']"

In [68]:
cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", s)
cleaned

"[{'entity_group': 'INS', 'score': 0.99988544, 'word': 'University of British Columbia', 'start': 32, 'end': 62}, {'entity_group': 'SUBC', 'score': 0.99957687, 'word': 'Vancouver', 'start': 64, 'end': 73}, {'entity_group': 'COU', 'score': 0.9991843, 'word': 'Canada', 'start': 75, 'end': 81}, {'entity_group': 'INS', 'score': 0.9996547, 'word': 'Hereditary Cancer', 'start': 112, 'end': 129}, {'entity_group': 'INS', 'score': 0.9165015, 'word': 'BC Cancer', 'start': 131, 'end': 140}, {'entity_group': 'INS', 'score': 0.9998889, 'word': 'University of British Columbia', 'start': 196, 'end': 226}, {'entity_group': 'SUBC', 'score': 0.99966955, 'word': 'Vancouver', 'start': 228, 'end': 237}, {'entity_group': 'COU', 'score': 0.9899244, 'word': 'Canada', 'start': 239, 'end': 245}, {'entity_group': 'INS', 'score': 0.9998265, 'word': 'Instituto de Investigação e Inovação em Saúde', 'start': 253, 'end': 298}, {'entity_group': 'INS', 'score': 0.9998478, 'word': 'Institute of Molecular Pathology and Immunology', 'start': 301, 'end': 348}, {'entity_group': 'INS', 'score': 0.9998773, 'word': 'University of Porto', 'start': 372, 'end': 391}, {'entity_group': 'SUBC', 'score': 0.9993736, 'word': 'Porto', 'start': 393, 'end': 398}, {'entity_group': 'COU', 'score': 0.99635196, 'word': 'Portugal', 'start': 400, 'end': 408}, {'entity_group': 'INS', 'score': 0.9998352, 'word': 'Instituto de Investigação e Inovação em Saúde', 'start': 416, 'end': 461}, {'entity_group': 'INS', 'score': 0.99979734, 'word': 'University of Porto', 'start': 463, 'end': 482}, {'entity_group': 'SUBC', 'score': 0.99932814, 'word': 'Porto', 'start': 484, 'end': 489}, {'entity_group': 'COU', 'score': 0.9995546, 'word': 'Portugal', 'start': 491, 'end': 499}]"

In [91]:
query = ast.literal_eval(cleaned)[6]["word"]
query

'Vancouver'

In [92]:
connection = psycopg2.connect(database="ror_institutions", user="postgres", password=KEY_POSTGRES, host="localhost", port=5432)
cursor = connection.cursor()
cursor.execute("SELECT DISTINCT ON (institution_id) name FROM public.institution_names WHERE name = %s;", (query,))
record = cursor.fetchall()
record

[]

In [53]:
ast.literal_eval(cleaned)[0]

{'entity_group': 'INS',
 'score': 0.99988544,
 'word': 'University of British Columbia',
 'start': 32,
 'end': 62}

In [106]:
df['Institutions_db'] = [[] for _ in range(len(df))]
df['Countries_db'] = [[] for _ in range(len(df))]

for row in tqdm(range(len(df))):
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.iloc[row]["NER_BERT"])
    for NER_result in ast.literal_eval(cleaned):
        if NER_result['entity_group'] == 'INS':
            query = NER_result['word']
            connection = psycopg2.connect(database="ror_institutions", user="postgres", password=KEY_POSTGRES, host="localhost", port=5432)
            cursor = connection.cursor()
            cursor.execute(f"SELECT * FROM institution_names WHERE name = '{query}';")
            record = cursor.fetchall()
            institutions_db = []
            for el in record:
                institutions_db.append(el[3])
            institutions_db = list(set(institutions_db))
            if len(institutions_db) == 1:
                df.iloc[row]['Institutions_db'].append(institutions_db)
                i = 0
                while i == 0:
                    for el in record:
                        if institutions_db[0] in el:
                            new_query = el[2]
                            connection = psycopg2.connect(database="ror_institutions", user="postgres", password=KEY_POSTGRES, host="localhost", port=5432)
                            cursor = connection.cursor()
                            cursor.execute(f"SELECT country_name FROM institution_locations WHERE country_name = '{new_query}';")
                            new_record = cursor.fetchall()
                            if len(new_record) > 0:
                                df.iloc[row]['Countries_db'].append(new_record[0][5])
                                i += 1

  2%|█▌                                                                              | 2/103 [02:20<1:58:08, 70.18s/it]

KeyboardInterrupt:

# WITH CACHE

In [ ]:
# Create empty columns
df['Institutions_db'] = [[] for _ in range(len(df))]
df['Countries_db'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

# Cache to avoid repeated DB hits
institution_cache = {}

for row in tqdm(range(len(df))):
    print(row)
    if pd.isna(df.at[row, "NER_BERT"]):    
        continue
        
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)
    
    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        
        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
    
        # ---- Cache lookup ----
        if query in institution_cache:
            institutions_db, countries_db = institution_cache[query]
        else:
            # Parameterized query
            cursor.execute(
                "SELECT * FROM institution_names WHERE name = %s;",
                (query,)
            )
            records = cursor.fetchall()
    
            institutions_db = list({el[1] for el in records})
            print(institutions_db)
            
            institutions_id = list({el[0] for el in records})
            print(institutions_id)
            
            countries_db = []
    
            if len(set(institutions_id)) == 1:
    
                # Find related country via institution_locations
                for el in records:
                    #if institution_id in el:
                    new_query = el[0]
    
                    cursor.execute(
                        "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                        (new_query,)
                    )
                    location_records = cursor.fetchall()
    
                    if location_records:
                        countries_db.append(location_records[0][0])
                        break

            
            institution_cache[query] = (institutions_db, countries_db)
    
        # Append results safely
        if institutions_db:
            df.at[row, 'Institutions_db'].append(institutions_db[0])
        if countries_db:
            df.at[row, 'Countries_db'].append(countries_db[0])
            
cursor.close()
connection.close()

# NO CACHE

In [ ]:
# Create empty columns
df['Institutions_db'] = [[] for _ in range(len(df))]
df['Countries_db'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

for row in tqdm(range(len(df))):
    if pd.isna(df.at[row, "NER_BERT"]):    
        continue

    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC']
    cou_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU']

    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
        
        # Parameterized query
        cursor.execute(
            "SELECT * FROM institution_names WHERE name = %s;",
            (query,)
        )
        records = cursor.fetchall()


        institutions_name = list({el[1] for el in records})
        institutions_id = list({el[0] for el in records})
        countries_db = []

        if len(set(institutions_id)) == 1:
            new_query = institutions_id[0]
    
            cursor.execute(
                "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                (new_query,)
            )
            
            location_records = cursor.fetchall()
    
            if location_records:
                countries_db.append(location_records[0][0]) #Check if this is the correct index for country_name
                break

In [ ]:
# Create empty columns
df['Institutions_db'] = [[] for _ in range(len(df))]
df['Countries_db'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

for row in tqdm(range(len(df))):
    print(row)
    if pd.isna(df.at[row, "NER_BERT"]):    
        continue
        
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)

    subc_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'SUBC']
    cou_ner_results = [ner.get('word') for ner in ner_results if ner.get('entity_group') == 'COU']
    
    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        
        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
    
        # Parameterized query
        cursor.execute(
            "SELECT * FROM institution_names WHERE name = %s;",
            (query,)
        )
        records = cursor.fetchall()
    
        institutions_db = list({el[1] for el in records})
        print(institutions_db)
            
        institutions_id = list({el[0] for el in records})
        print(institutions_id)
            
        countries_db = []
    
        if len(set(institutions_id)) == 1:
    
            # Find related country via institution_locations
            for el in records:
                #if institution_id in el:
                new_query = el[0]
    
                cursor.execute(
                    "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                    (new_query,)
                )
                location_records = cursor.fetchall()
    
                if location_records:
                    countries_db.append(location_records[0][0])
                    break

        if len(institutions_id) == 0:

            # Call the database again with a fuzzy string match
            cursor.execute(
                "SELECT * FROM institution_names WHERE levenshtein(name, %s) <= 2;",
                (query,)
            )
            records = cursor.fetchall()

            institutions_db = list({el[1] for el in records})
            print(institutions_db)
                
            institutions_id = list({el[0] for el in records})
            print(institutions_id)
                
            countries_db = []
            if len(set(institutions_id)) == 1:
                
                # Find related country via institution_locations
                for el in records:
                    #if institution_id in el:
                    new_query = el[0]
    
                    cursor.execute(
                        "SELECT country_name FROM institution_locations WHERE institution_id = %s;",
                        (new_query,)
                    )
                    location_records = cursor.fetchall()
    
                    if location_records and location_records[0][0] in cou_ner_results:
                        countries_db.append(location_records[0][0])
                        break
                    else:
                        institutions_db = None
    
        # Append results safely
        if institutions_db and institutions_db[0] not in df.at[row, 'Institutions_db']:
            df.at[row, 'Institutions_db'].append(institutions_db[0])
            if countries_db:
                df.at[row, 'Countries_db'].append(countries_db[0])
            
cursor.close()
connection.close()

In [187]:
df[["NER_BERT", "Institutions_man", "Institutions_db"]]

,NER_BERT,Institutions_man,Institutions_db
0,[],NaN,[]
1,[],NaN,[]
2,"[{'entity_group': 'INS', 'score': np.float32(0.99988544), 'word': 'University of British Columbia', 'start': 32, 'end': 62}, {'entity_group': 'SUBC', 'score': np.float32(0.99957687), 'word': 'Vancouver', 'start': 64, 'end': 73}, {'entity_group': 'COU', 'score': np.float32(0.9991843), 'word': 'Canada', 'start': 75, 'end': 81}, {'entity_group': 'INS', 'score': np.float32(0.9996547), 'word': 'Hereditary Cancer', 'start': 112, 'end': 129}, {'entity_group': 'INS', 'score': np.float32(0.9165015), ...","['Instituto de Investigação e Inovação em Saúde', 'University of Porto', 'University of British Columbia', 'BC Cancer', 'Institute of Molecular Pathology and Immunology']","[University of British Columbia, University of Porto]"
3,"[{'entity_group': 'INS', 'score': np.float32(0.9998616), 'word': ""Cincinnati Children ' s Hospital Medical Center"", 'start': 84, 'end': 129}, {'entity_group': 'INS', 'score': np.float32(0.9997229), 'word': 'University of Cincinnati', 'start': 132, 'end': 156}, {'entity_group': 'SUBC', 'score': np.float32(0.9995741), 'word': 'Cincinnati', 'start': 178, 'end': 188}, {'entity_group': 'SUBC', 'score': np.float32(0.9996165), 'word': 'Ohio', 'start': 190, 'end': 194}, {'entity_group': 'INS', 'scor...","[""Cincinnati Children's Hospital Medical Center"", 'University of Cincinnati', ""Children's Hospital Los Angeles"", 'USC', 'Aflac Cancer and Blood Disorders Center', ""Children's Healthcare of Atlanta"", 'Emory University', 'GoBroad Healthcare Group', 'GoBroad Hospital']","[University of Cincinnati, Emory University]"
4,"[{'entity_group': 'INS', 'score': np.float32(0.92480797), 'word': 'Independent Contractor', 'start': 0, 'end': 22}, {'entity_group': 'SUBC', 'score': np.float32(0.9978091), 'word': 'Ashburn', 'start': 24, 'end': 31}, {'entity_group': 'COU', 'score': np.float32(0.9990839), 'word': 'USA', 'start': 37, 'end': 40}, {'entity_group': 'INS', 'score': np.float32(0.99686503), 'word': 'University of Pennsylvania', 'start': 104, 'end': 130}, {'entity_group': 'SUBC', 'score': np.float32(0.99908435), 'wo...","['University of Oklahoma Health Sciences Center', 'University at Buffalo', 'Battelle Memorial Institute', 'University of Memphis', 'Rutgers Institute for Nicotine & Tobacco Studies', 'Rutgers Biomedical and Health Sciences', 'University of Chicago', 'TSET Health Promotion Research Center', 'Stephenson Cancer Center', 'University of Pennsylvania']","[University of Pennsylvania, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, University of Memphis, Battelle Memorial Institute, University of Chicago, Rutgers Biomedical and Health Sciences]"
5,"[{'entity_group': 'INS', 'score': np.float32(0.9999144), 'word': 'CONAHCYT', 'start': 0, 'end': 8}, {'entity_group': 'INS', 'score': np.float32(0.99088496), 'word': 'Center for Research on Population Health', 'start': 11, 'end': 51}, {'entity_group': 'INS', 'score': np.float32(0.9998376), 'word': 'National Institute of Public Health', 'start': 53, 'end': 88}, {'entity_group': 'SUBC', 'score': np.float32(0.9997936), 'word': 'Cuernavaca', 'start': 90, 'end': 100}, {'entity_group': 'COU', 'scor...","['Center for Research on Population Health', 'National Institute of Public Health', 'CONAHCYT', 'Institute for Research in Applied Mathematics and Systems', 'Universidad Nacional Autonoma de Mexico', 'Center for Research on Evaluation and Surveys', 'Harvard']","[CONAHCYT, National Institute of Public Health, Universidad Nacional Autónoma de México]"
6,"[{'entity_group': 'INS', 'score': np.float32(0.999654), 'word': 'Labex TOUCAN', 'start': 0, 'end': 12}, {'entity_group': 'INS', 'score': np.float32(0.8912306), 'word': 'ANR', 'start': 14, 'end': 17}, {'entity_group': 'SUBC', 'score': np.float32(0.9987576), 'word': 'Toulouse', 'start': 19, 'end': 27}, {'entity_group': 'COU', 'score': np.float32(0.99966335), 'word': 'France', 'start': 29, 'end': 35}, {'entity_group': 'INS', 'score': np.float32(0.99942905), 'word': 'Université de Toulouse', 'st...","['CRCT', 'Université de Toulouse', 'Inserm', 'CNRS', 'Centre de Recherches en Cancérologie de Toulouse', 'Labex TOUCAN', 'Institut Universitaire du Cancer de Toulouse-Oncopole (IUCT-O)']","[ANR, Université de Toulouse, Inserm, CNRS, Centre de Recherche en Cancérologie de Toulouse, TOCA, Curium]"
7,"[{'entity_group': 'INS', 'score': np.float32(0.99685305), 'word': 'First Affiliated Hospital of Xinjiang Medical University', 'start': 31, 'end': 87}, {'entity_group': 'SUBC', 'score': np.float32(0.99980646), 'word': 'Xinjiang', 'start': 89, 'end': 97}, {'entity_group': 'COU', 'score': np.float32(0.999469), 'word': 'China', 'start': 107, 'end': 112}, {'entity_group': 'EMA', 'score': np.float32(0.999883), 'word': '294198014 @ qq. com..', 'start': 114, 'end': 132}, {'entity_group': 'INS', 'sco...",['First Affiliated Hospital of Xinjiang Medical University'],[First Affiliated Hospital of Xinjiang Medical University]
8,"[{'entity_group': 'INS', 'score': np.float32(0.9998862), 'word': 'Institute of Developmental Biology and Biomedical Sciences', 'start': 44, 'end': 102}, {'entity_group': 'INS', 'score': np.float32(0.9998122), 'word': 'University of Warsaw', 'start': 104, 'end': 124}, {'entity_group': 'COU', 'score': np.float32(0.9888747), 'word': 'Poland', 'start': 126, 'end': 132}, {'entity_group': 'EMA', 'score': np.float32(0.991976), 'word': 'e. brzoska - wojt @ uw. edu. pl.', 'start': 154, 'end': 179}, {...","['Institute of Developmental Biology and Biomedical Sciences', 'University of Warsaw']",[University of Warsaw]
9,"[{'entity_group': 'INS', 'score': np.float32(0.99987465), 'word': 'Chang Gung University', 'start': 20, 'end': 41}, {'entity_group': 'SUBC', 'score': np.float32(0.99911875), 'word': 'TaoYuan', 'start': 43, 'end': 50}, {'entity_group': 'COU', 'score': np.float32(0.99478936), 'word': 'Taiwan', 'start': 56, 'end': 62}, {'entity_group': 'INS', 'score': np.float32(0.9962244), 'word': 'Chang Gung Memorial Hospital - Linkou', 'start': 95, 'end': 130}, {'entity_group': 'SUBC', 'score': np.float32(0....","['Chang Gung Memorial Hospital-Linkou', 'Chang Gung University']","[Chang Gung University, Chang Gung Memorial Hospital]"
10,"[{'entity_group': 'INS', 'score': np.float32(0.9998967), 'word': 'Ruhr University Bochum', 'start': 0, 'end': 22}, {'entity_group': 'INS', 'score': np.float32(0.99989384), 'word': 'BG University Hospital Bergmannsheil', 'start': 49, 'end': 85}, {'entity_group': 'SUBC', 'score': np.float32(0.99976104), 'word': 'Bochum', 'start': 87, 'end': 93}, {'entity_group': 'COU', 'score': np.float32(0.99983776), 'word': 'Germany', 'start': 95, 'end': 102}, {'entity_group': 'INS', 'score': np.float32(0.99...","['Ruhr University Bochum', 'BG University Hospital Bergmannsheil', 'Friedrich-Baur-Institute', 'Ludwig-Maximilians University', 'Medical Genetics Center Munich', 'University Hospital of Bonn', 'Hannover Medical School', 'Clinic and Policlinic for Radiation Therapy and Radiooncology', 'University of Düsseldorf', 'Kantonsspital St. Gallen', 'University of Würzburg', 'University of Bonn Medical Center', 'University Medical Center Göttingen']",[Ruhr University Bochum]
11,"[{'entity_group': 'INS', 'score': np.float32(0.9999018), 'word': 'Diabetes Research Institute', 'start': 11, 'end': 38}, {'entity_group': 'INS', 'score': np.float32(0.99989736), 'word': 'IRCCS Ospedale San Raffaele', 'start': 40, 'end': 67}, {'entity_group': 'INS', 'score': np.float32(0.9800417), 'word': 'Vita - Salute San Raffaele University', 'start': 72, 'end': 107}, {'entity_group': 'SUBC', 'score': np.float32(0.99977237), 'word': 'Milan', 'start': 109, 'end': 114}, {'entity_group': 'COU...","['IRCCS', 'Ospedale San Raffaele', 'Vita-Salute San Raffaele University']","[IRCCS Ospedale San Raffaele, Vita-Salute San Raffaele University]"
12,"[{'entity_group': 'INS', 'score': np.float32(0.9997718), 'word': 'University of Adelaide', 'start': 42, 'end': 64}, {'entity_group': 'INS', 'score': np.float32(0.99986154), 'word': 'Queen Elizabeth Hospital', 'start': 66, 'end': 90}, {'entity_group': 'SUBC', 'score': np.float32(0.9980761), 'word': 'Woodville', 'start': 92, 'end': 101}, {'entity_group': 'COU', 'score': np.float32(0.9590922), 'word': 'Australia', 'start': 109, 'end': 118}]","['University of Adelaide', 'Queen Elizabeth Hospital']","[University of Adelaide, Queen Elizabeth Hospital]"
13,"[{'entity_group': 'INS', 'score': np.float32(0.9986978), 'word': 'University of Zimbabwe', 'start': 36, 'end': 58}, {'entity_group': 'SUBC', 'score': np.float32(0.99964225), 'word': 'Harare', 'start': 90, 'end': 96}]",['University of Zimbabwe'],[University of Zimbabwe]
14,"[{'entity_group': 'INS', 'score': np.float32(0.999794), 'word': 'University of Tokyo Hospital', 'start': 23, 'end': 51}, {'entity_group': 'SUBC', 'score': np.float32(0.9991283), 'word': 'Tokyo', 'start': 53, 'end': 58}, {'entity_group': 'COU', 'score': np.float32(0.999602), 'word': 'Japan', 'start': 60, 'end': 65}, {'entity_group': 'EMA', 'score': np.float32(0.99992436), 'word': 'kueki - tky @ umin. ac. jp', 'start': 67, 'end': 87}]",['University of Tokyo Hospital'],[University of Tokyo Hospital]
15,"[{'entity_group': 'INS', 'score': np.float32(0.99915946), 'word': 'University Hospital Centre of Grenoble', 'start': 61, 'end': 99}, {'entity_group': 'SUBC', 'score': np.float32(0.99982053), 'word': 'Grenoble', 'start': 101, 'end': 109}, {'entity_group': 'COU', 'score': np.float32(0.9998185), 'word': 'France', 'start': 111, 'end': 117}, {'entity_group': 'EMA', 'score': np.float32(0.99992245), 'word': 'dominique. plantaz @ ujf - grenoble. fr', 'start': 119, 'end': 152}]",['University Hospital Centre of Grenoble'],[]
16,"[{'entity_group': 'INS', 'score': np.float32(0.9990846), 'word': 'Harvard', 'start': 81, 'end': 88}, {'entity_group': 'SUBC', 'score': np.float32(0.99964476), 'word': 'Boston', 'start': 137, 'end': 143}, {'entity_group': 'COU', 'score': np.float32(0.99863833), 'word': 'USA', 'start': 155, 'end': 158}]",['Harvard'],[]
17,"[{'entity_group': 'INS', 'score': np.float32(0.99982816), 'word': 'University of Washington', 'start': 67, 'end': 91}, {'entity_group': 'SUBC', 'score': np.float32(0.9995012), 'word': 'Seattle', 'start': 93, 'end': 100}, {'entity_group': 'COU', 'score': np.float32(0.9994312), 'word': 'USA', 'start': 102, 'end': 105}]",['University of Washington'],[University of Washington]
18,"[{'entity_group': 'INS', 'score': np.float32(0.9997824), 'word': 'University of Würzburg', 'start': 28, 'end': 50}, {'entity_group': 'COU', 'score': np.float32(0.9992975), 'word': 'Germany', 'start': 52, 'end': 59}, {'entity_group': 'EMA', 'score': np.float32(0.9998605), 'word': 'willner _ j @ klinik. uni - wuerzburg. de', 'start': 61, 'end': 94}]",['University of Würzburg'],[University of Würzburg]
19,"[{'entity_group': 'INS', 'score': np.float32(0.9999091), 'word': 'Mannheim Medical Center', 'start': 34, 'end': 57}, {'entity_group': 'INS', 'score': np.float32(0.99973434), 'word': 'University of Heidelberg', 'start': 59, 'end': 83}, {'entity_group': 'COU', 'score': np.float32(0.9992642), 'word': 'Germany', 'start': 85, 'end': 92}, {'entity_group': 'EMA', 'score': np.float32(0.99992317), 'word': 'frank. lohr @ radonk. ma. uni - heidelberg. de', 'start': 94, 'end': 132}]","['Mannheim Medical Center', 'University of Heidelberg']",[]
20,[],NaN,[]
21,"[{'entity_group': 'INS', 'score': np.float32(0.99970484), 'word': 'Norwegian University of Science and Technology', 'start': 50, 'end': 96}, {'entity_group': 'SUBC', 'score': np.float32(0.9997588), 'word': 'Trondheim', 'start': 98, 'end': 107}, {'entity_group': 'COU', 'score': np.float32(0.99974316), 'word': 'Norway', 'start': 109, 'end': 115}, {'entity_group': 'EMA', 'score': np.float32(0.99992776), 'word': 'lars. vatten @ medisin. ntnu. no', 'start': 117, 'end': 144}]",['Norwegian University of Science and Technology'],[Norwegian University of Science and Technology]
22,"[{'entity_group': 'INS', 'score': np.float32(0.9997924), 'word': 'Duke University Medical Center', 'start': 34, 'end': 64}, {'entity_group': 'SUBC', 'score': np.float32(0.9995166), 'word': 'Durham', 'start': 66, 'end': 72}, {'entity_group': 'COU', 'score': np.float32(0.9985619), 'word': 'USA', 'start': 84, 'end': 87}, {'entity_group': 'EMA', 'score': np.float32(0.9999255), 'word': 'dewhirst @ radonc. duke. edu', 'start': 89, 'end': 113}]",['Duke University Medical Center'],[Duke University Medical Center]
23,"[{'entity_group': 'INS', 'score': np.float32(0.9999092), 'word': 'Hewitt Centre for Reproductive Medicine', 'start': 0, 'end': 39}, {'entity_group': 'INS', 'score': np.float32(0.99983853), 'word': ""Liverpool Women ' s Hospital"", 'start': 41, 'end': 67}, {'entity_group': 'SUBC', 'score': np.float32(0.9997131), 'word': 'Liverpool', 'start': 69, 'end': 78}, {'entity_group': 'COU', 'score': np.float32(0.9996008), 'word': 'UK', 'start': 80, 'end': 82}]","['Hewitt Centre for Reproductive Medicine', ""Liverpool Women's Hospital""]",[]
24,"[{'entity_group': 'INS', 'score': np.float32(0.99983144), 'word': 'University of Rochester', 'start': 23, 'end': 46}, {'entity_group': 'SUBC', 'score': np.float32(0.9997322), 'word': 'Rochester', 'start': 48, 'end': 57}, {'entity_group': 'COU', 'score': np.float32(0.99828666), 'word': 'USA', 'start': 69, 'end': 72}]",['University of Rochester'],[University of Rochester]
25,"[{'entity_group': 'INS', 'score': np.float32(0.9998438), 'word': 'Stavanger University Hospital', 'start': 53, 'end': 82}, {'entity_group': 'SUBC', 'score': np.float32(0.9998259), 'word': 'Stavanger', 'start': 84, 'end': 93}, {'entity_group': 'COU', 'score': np.float32(0.9997291), 'word': 'Norway', 'start': 95, 'end': 101}, {'entity_group': 'EMA', 'score': np.float32(0.9999293), 'word': 'ksoreide @ mac. com', 'start': 103, 'end': 119}]",['Stavanger University Hospital'],[Stavanger University Hospital]
26,"[{'entity_group': 'INS', 'score': np.float32(0.99989957), 'word': 'Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii', 'start': 0, 'end': 62}, {'entity_group': 'SUBC', 'score': np.float32(0.99956053), 'word': 'Kraków', 'start': 110, 'end': 116}, {'entity_group': 'COU', 'score': np.float32(0.9997154), 'word': 'Poland', 'start': 118, 'end': 124}]",['Klinika Nowotworów Układowych i Uogólnionych Centrum Onkologii'],[]
27,"[{'entity_group': 'INS', 'score': np.float32(0.99990773), 'word': 'Akademii Medycznej w Gdańsku', 'start': 28, 'end': 56}, {'entity_group': 'SUBC', 'score': np.float32(0.99959666), 'word': 'Gdańsk', 'start': 80, 'end': 86}, {'entity_group': 'COU', 'score': np.float32(0.9995914), 'word': 'Poland', 'start': 88, 'end': 94}, {'entity_group': 'EMA', 'score': np.float32(0.9999199), 'word': 'aleksandra. modlinska @ amg. gda. pl', 'start': 96, 'end': 127}]",['Akademii Medycznej w Gdańsku'],[]
28,"[{'entity_group': 'INS', 'score': np.float32(0.9996951), 'word': 'Vienna Medical University', 'start': 33, 'end': 58}, {'entity_group': 'SUBC', 'score': np.float32(0.9996916), 'word': 'Vienna', 'start': 60, 'end': 66}, {'entity_group': 'COU', 'score': np.float32(0.99970764), 'word': 'Austria', 'start': 68, 'end': 75}, {'entity_group': 'EMA', 'score': np.float32(0.999929), 'word': 'christian. singer @ meduniwien. ac. at', 'start': 77, 'end': 110}]",['Vienna Medical University'],[]
29,"[{'entity_group': 'INS', 'score': np.float32(0.9998878), 'word': 'Eastern Hepatobiliary Surgery Hospital', 'start': 37, 'end': 75}, {'entity_group': 'INS', 'score': np.float32(0.9998667), 'word': 'Second Military Medical University', 'start': 77, 'end': 111}, {'entity_group': 'SUBC', 'score': np.float32(0.99965954), 'word': 'Shanghai', 'start': 113, 'end': 121}, {'entity_group': 'COU', 'score': np.float32(0.99929285), 'word': 'China', 'start': 130, 'end': 135}]","['Eastern Hepatobiliary Surgery Hospital', 'Second Military Medical University']","[Eastern Hepatobiliary Surgery Hospital, Second Military Medical University]"
30,[],NaN,[]
31,"[{'entity_group': 'INS', 'score': np.float32(0.9998843), 'word': 'Center for Gerontology and Health Care Research', 'start': 0, 'end': 47}, {'entity_group': 'INS', 'score': np.float32(0.99792403), 'word': 'Brown University', 'start': 49, 'end': 65}, {'entity_group': 'SUBC', 'score': np.float32(0.99962175), 'word': 'Providence', 'start': 79, 'end': 89}, {'entity_group': 'SUBC', 'score': np.float32(0.9994639), 'word': 'Rhode Island', 'start': 91, 'end': 103}, {'entity_group': 'COU', 'score': n...","['Center for Gerontology and Health Care Research', 'Brown University']",[Brown University]
32,"[{'entity_group': 'INS', 'score': np.float32(0.999914), 'word': 'Tianjin Lung Cancer Institute', 'start': 76, 'end': 105}, {'entity_group': 'INS', 'score': np.float32(0.9987999), 'word': 'Tianjin Medical University General Hospital', 'start': 107, 'end': 150}, {'entity_group': 'SUBC', 'score': np.float32(0.9997476), 'word': 'Tianjin', 'start': 152, 'end': 159}, {'entity_group': 'COU', 'score': np.float32(0.99974626), 'word': 'China', 'start': 168, 'end': 173}]","['Tianjin Lung Cancer Institute', 'Tianjin Medical University General Hospital']",[Tianjin Medical University General Hospital]
33,"[{'entity_group': 'INS', 'score': np.float32(0.9998882), 'word': 'Evidence Based Medicine Center', 'start': 0, 'end': 30}, {'entity_group': 'INS', 'score': np.float32(0.99991584), 'word': 'Lanzhou University', 'start': 34, 'end': 52}, {'entity_group': 'SUBC', 'score': np.float32(0.99971026), 'word': 'Lanzhou', 'start': 54, 'end': 61}, {'entity_group': 'COU', 'score': np.float32(0.99976355), 'word': 'China', 'start': 70, 'end': 75}, {'entity_group': 'INS', 'score': np.float32(0.9999036), 'wor...","['Evidence Based Medicine Center', 'Lanzhou University']",[Lanzhou University]
34,"[{'entity_group': 'SUBC', 'score': np.float32(0.9015557), 'word': 'Wellington', 'start': 23, 'end': 33}, {'entity_group': 'COU', 'score': np.float32(0.99706423), 'word': 'New Zealand', 'start': 54, 'end': 65}]",NaN,[]
35,"[{'entity_group': 'INS', 'score': np.float32(0.9998917), 'word': 'Royal North Brisbane Hospital', 'start': 0, 'end': 29}, {'entity_group': 'SUBC', 'score': np.float32(0.9997131), 'word': 'Herston', 'start': 31, 'end': 38}, {'entity_group': 'SUBC', 'score': np.float32(0.9992059), 'word': 'Queensland', 'start': 40, 'end': 50}]",['Royal North Brisbane Hospital'],[]
36,"[{'entity_group': 'INS', 'score': np.float32(0.9998993), 'word': 'Azienda Ospedaliero Universitaria S Maria della Misericordia', 'start': 26, 'end': 86}, {'entity_group': 'SUBC', 'score': np.float32(0.99960965), 'word': 'Udine', 'start': 88, 'end': 93}, {'entity_group': 'COU', 'score': np.float32(0.99979585), 'word': 'Italy', 'start': 95, 'end': 100}, {'entity_group': 'EMA', 'score': np.float32(0.99992466), 'word': 'marega. alessandra @ aoud. sanita. fvg. it', 'start': 102, 'end': 138}]",['Azienda Ospedaliero Universitaria S Maria della Misericordia'],[]
37,"[{'entity_group': 'INS', 'score': np.float32(0.99989545), 'word': 'Universitá degli Studi di Palermo', 'start': 88, 'end': 121}, {'entity_group': 'SUBC', 'score': np.float32(0.9996544), 'word': 'Palermo', 'start': 123, 'end': 130}, {'entity_group': 'COU', 'score': np.float32(0.99977666), 'word': 'Italy', 'start': 132, 'end': 137}, {'entity_group': 'EMA', 'score': np.float32(0.99992657), 'word': 'ailomonte @ unipa. it', 'start': 139, 'end': 157}]",['Universitá degli Studi di Palermo'],[Università degli Studi di Palermo]
38,"[{'entity_group': 'INS', 'score': np.float32(0.99981236), 'word': 'University Medical Center Hamburg - Eppendorf', 'start': 56, 'end': 99}, {'entity_group': 'COU', 'score': np.float32(0.9995703), 'word': 'Germany', 'start': 101, 'end': 108}]",['University Medical Center Hamburg-Eppendorf'],[University Medical Center Hamburg-Eppendorf]
39,"[{'entity_group': 'EMA', 'score': np.float32(0.9999186), 'word': 'cjpeng @ wiley. com', 'start': 0, 'end': 16}]",NaN,[]

In [182]:
df.iloc[4]["Authors"]

"[{'Name': 'Amy M Cohn', 'Affiliation': ['Department of Pediatrics, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.', 'TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Hoda Elmasry', 'Affiliation': ['Department of Pediatrics, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.', 'Independent Contractor, Ashburn, VA, USA.']}, {'Name': 'Rebecca Ashare', 'Affiliation': ['Department of Psychology, University at Buffalo, Buffalo, NY, USA.']}, {'Name': 'Wallace Pickworth', 'Affiliation': ['Battelle Memorial Institute, Baltimore, MD, USA.']}, {'Name': 'James G Murphy', 'Affiliation': ['Department of Psychology, University of Memphis, Memphis, TN, USA.']}, {'Name': 'Andrea C Villanti', 'Affiliation': ['Rutgers Institute for Nicotine & Tobacco Studies, Rutgers Biomedical and Health Sciences, New Brunswick, NJ, USA.']}, {'Name': 'Donald Hedeker', 'Affiliation': ['The Department of Public Health Sciences, University of Chicago, Chicago, IL, USA.']}, {'Name': 'Delaney Dunn', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Riley Wyatt', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Taylor Niznik', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Whitney D Margaritis', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Michael A Smith', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Sarah J Ehlke', 'Affiliation': ['TSET Health Promotion Research Center, Stephenson Cancer Center, University of Oklahoma Health Sciences Center, Oklahoma City, OK, USA.']}, {'Name': 'Janet Audrain-McGovern', 'Affiliation': ['Department of Psychiatry, Perelman School of Medicine of the University of Pennsylvania, Philadelphia, PA, USA.']}]"

In [188]:
df[["Countries_man", "Countries_db"]]

,Countries_man,Countries_db
0,NaN,[]
1,NaN,[]
2,"['Portugal', 'Portugal', 'Canada', 'Canada', 'Portugal']","[Canada, Portugal]"
3,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'China', 'China']","[United States, United States]"
4,"['United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States', 'United States']","[United States, United States, United States, United States, United States, United States, United States]"
5,"['Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'Mexico', 'United States']","[Mexico, Mexico]"
6,"['France', 'France', 'France', 'France', 'France', 'France', 'France']","[United States, France, France]"
7,['China'],[China]
8,"['Poland', 'Poland']",[Poland]
9,"['Taiwan', 'Taiwan']",[Taiwan]
10,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Switzerland', 'Germany', 'Germany', 'Germany']",[Germany]
11,"['Italy', 'Italy', 'Italy']","[Italy, Italy]"
12,"['Autralia', 'Autralia']",[Australia]
13,['Zimbabwe'],[Zimbabwe]
14,['Japan'],[Japan]
15,['France'],[]
16,['United States'],[]
17,['United States'],[United States]
18,['Germany'],[Germany]
19,"['Germany', 'Germany']",[]
20,NaN,[]
21,['Norway'],[Norway]
22,['United States'],[]
23,"['United Kingdom', 'United Kingdom']",[]
24,['United States'],[United States]
25,['Norway'],[Norway]
26,['Poland'],[]
27,['Poland'],[]
28,['Austria'],[]
29,"['China', 'China']","[China, China]"
30,NaN,[]
31,"['United States', 'United States']",[United States]
32,"['China', 'China']",[China]
33,"['China', 'China']",[China]
34,['New Zealand'],[]
35,['Australia'],[]
36,['Italy'],[]
37,['Italy'],[Italy]
38,['Germany'],[Germany]
39,NaN,[]
40,"['Czechia', 'Czechia']",[Czechia]
41,['Australia'],[Australia]
42,['Portugal'],[Portugal]
43,"['United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
44,"['Germany', 'Germany', 'Germany', 'Germany', 'Germany', 'Germany']","[Germany, Switzerland, Germany, Germany, Switzerland]"
45,"['United States', 'United States', 'United States']","[United States, United States]"
46,"['China', 'China']",[China]
47,"['China', 'China', 'China', 'China', 'China', 'China']",[China]
48,NaN,[]
49,NaN,[]
50,"['Pakistan', 'Pakistan']",[]
51,"['Türkiye', 'Türkiye', 'Türkiye']","[Türkiye, Türkiye]"
52,NaN,[]
53,NaN,[]
54,"['United States', 'United States', 'United States', 'United States', 'United States']",[United States]
55,"['The Netherlands', 'The Netherlands', 'The Netherlands']","[The Netherlands, The Netherlands, The Netherlands]"
56,NaN,[]
57,NaN,[]
58,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom']","[United Kingdom, United Kingdom]"
59,"['Spain', 'Germany', 'Spain', 'Spain', 'Spain', 'Germany', 'Germany', 'Germany', 'United States', 'United States']","[Spain, Spain, Germany]"
60,"['United Kingdom', 'United Kingdom', 'United Kingdom', 'Sweden', 'Sweden', 'Sweden']","[Sweden, Sweden, Sweden]"
61,"['Spain', 'Spain', 'Spain', 'Spain', 'Japan', 'Switzerland', 'United States', 'Spain']","[Spain, Japan, United States]"
62,['India'],[India]
63,"['Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan', 'Japan']","[Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan, Japan]"
64,['United States'],[]
65,['United States'],[United States]
66,"['Ethiopia', 'Sweden', 'Sweden', 'Ethiopia', 'Ethiopia']","[Sweden, Ethiopia, Ethiopia, Sweden]"
67,['Italy'],[]
68,"['United States', 'United States']",[United States]
69,"['China', 'China', 'China']","[China, China, China]"
70,"['China', 'China', 'China', 'China']",[]
71,"['China', 'China', 'China', 'China']",[China]
72,['Austria'],[]
73,"['United States', 'United States']",[United States]
74,"['United States', 'United States', 'United States', 'United States', 'United States']",[United States]
75,"['United States', 'United States']",[United States]
76,"['China', 'China', 'China', 'China', 'China']",[China]
77,"['United States', 'United States', 'United States', 'United States']","[United States, United States, United States]"
78,['United States'],[United States]
79,['United States'],[]
80,NaN,[]
81,NaN,[]
82,"['China', 'China', 'China']","[China, China]"
83,"['Brazil', 'Brazil', 'Brazil', 'Brazil']",[Brazil]
84,"['China', 'China', 'China', 'China', 'China', 'China', 'China']","[China, China, China, China]"
85,"['France', 'France', 'France', 'France', 'France', 'France', 'France', 'Germany', 'Germany', 'Czechia', 'Czechia', 'France', 'France', 'France', 'France', 'France', 'France']","[Czechia, France, Germany, Germany, France, France, France, France, France, France, France, France, France, France]"
86,"['Norway', 'Norway', 'Norway', 'Norway', 'Norway']",[Norway]
87,['United States'],[United States]
88,"['Romania', 'Romania', 'Romania', 'Romania']","[Romania, Romania, Iran]"
89,"['Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan']","[Taiwan, United States, Taiwan]"
90,"['China', 'China', 'China']",[]
91,"['United States', 'Pakistan']","[Pakistan, United States]"
92,NaN,[]
93,NaN,[]
94,['United States'],[United States]
95,['United States'],[United States]
96,['United States'],[]
97,"['United States', 'United States']",[United States]
98,['Mexico'],[]
99,['The Netherlands'],[]
100,['Switzerland'],[Switzerland]
101,['United States'],[United States]
102,[],[]

In [ ]:
# Create empty columns
df['Institutions_db'] = [[] for _ in range(len(df))]
df['Countries_db'] = [[] for _ in range(len(df))]

# Open ONE connection
connection = psycopg2.connect(
    database="ror_institutions",
    user="postgres",
    password=KEY_POSTGRES,
    host="localhost",
    port=5432
)
cursor = connection.cursor()

# Cache to avoid repeated DB hits
institution_cache = {}

for row in tqdm(range(len(df))):
    if pd.isna(df.at[row, "NER_BERT"]):    
        continue
        
    cleaned = re.sub(r"np\.float\d+\((.*?)\)", r"\1", df.at[row, "NER_BERT"])
    ner_results = ast.literal_eval(cleaned)
    
    for ner in ner_results:
        if ner.get('entity_group') != 'INS':
            continue
    
        query = ner.get('word')

        
        if '\'' in query:
            query = re.sub("\'", "\'\'", query)
    
        # ---- Cache lookup ----
        if query in institution_cache:
            institutions_db, countries_db = institution_cache[query]
        else:
            # Parameterized query
            cursor.execute(
                "SELECT * FROM institution_names WHERE name = %s;",
                (query,)
            )
            records = cursor.fetchall()
    
            institutions_db = list({el[1] for el in records})
            institutions_id = list({el[0] for el in records})
            countries_db = []
    
            if len(set(institutions_db)) == 1:
    
                # Find related country via institution_locations
                for el in records:
                    if institution_id in el:
                        new_query = el[2]
    
                        cursor.execute(
                            "SELECT country_name FROM institution_locations WHERE country_name = %s;",
                            (new_query,)
                        )
                        location_records = cursor.fetchall()
    
                        if location_records:
                            countries_db.append(location_records[0][0])
                            break
    
            institution_cache[query] = (institutions_db, countries_db)
    
        # Append results safely
        if institutions_db:
            df.at[row, 'Institutions_db'].append(institutions_db)
        if countries_db:
            df.at[row, 'Countries_db'].append(countries_db)
            
cursor.close()
connection.close()